# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from psdbconnect import v1alpha1_pb2 as psdbconnect_dot_v1alpha1__pb2


class ConnectStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Sync = channel.unary_stream(
                '/psdbconnect.v1alpha1.Connect/Sync',
                request_serializer=psdbconnect_dot_v1alpha1__pb2.SyncRequest.SerializeToString,
                response_deserializer=psdbconnect_dot_v1alpha1__pb2.SyncResponse.FromString,
                )


class ConnectServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Sync(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConnectServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Sync': grpc.unary_stream_rpc_method_handler(
                    servicer.Sync,
                    request_deserializer=psdbconnect_dot_v1alpha1__pb2.SyncRequest.FromString,
                    response_serializer=psdbconnect_dot_v1alpha1__pb2.SyncResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'psdbconnect.v1alpha1.Connect', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Connect(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Sync(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/psdbconnect.v1alpha1.Connect/Sync',
            psdbconnect_dot_v1alpha1__pb2.SyncRequest.SerializeToString,
            psdbconnect_dot_v1alpha1__pb2.SyncResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
